services:
  # Backend Service (Spring Boot)
  - type: web
    name: chopade-lab-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: chopade-lab-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: chopade-lab-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: chopade-lab-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: chopade-lab-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: chopade-lab-db
          property: password



databases:
  # Database (PostgreSQL)
  - name: chopade-lab-db
    plan: free
    region: singapore
    databaseName: labdb
    user: labuser
